# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.42.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.42.0/nu_0_42_0_windows.msi
  InstallerSha256: AB3E671864D4F640BBE538B7FD55A48D632AAF8AEA4AF2A4226E29D03505447F
  ProductCode: '{887FE88C-CFEF-4324-BF6C-A27A010AD5BF}'
ManifestType: installer
ManifestVersion: 1.0.0

