# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: LovettSoftware.MyMoney.Net
PackageVersion: 1.1.0.81
FileExtensions:
- mmdb
Installers:
- Platform:
  - Windows.Universal
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: neutral
  InstallerType: msix
  InstallerUrl: https://github.com/clovett/MyMoney.Net/releases/download/1.1.0.81/MoneyPackage_1.1.0.81_AnyCPU.msixbundle
  InstallerSha256: AD27C8247172A847414C4902E33D849E31236AD5D7A2CB8EF7CCC82E302A0F11
  SignatureSha256: 3C8205DCF8E4385CC3808D2257EC8E824DF879E2DBF4F4E64F8FDFD124A31F7C
  PackageFamilyName: 43906ChrisLovett.MyMoney.Net_b2j8apzf1bbh6
ManifestType: installer
ManifestVersion: 1.0.0

