PackageIdentifier: Telerik.Fiddler.Everywhere.Internal
PackageVersion: 3.0.0-internal
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://downloads.getfiddler.com/win/Fiddler%20Everywhere%203.0.0-internal.exe
  InstallerSha256: d047830d6bd9acbe6ec7625102cfd4f5dc30c69ecaf432f7ae91a5157f8356ba
ManifestType: installer
ManifestVersion: 1.0.0
