# Created with YamlCreate.ps1 v2.0.4 $debug=NVS0.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.1.0.schema.json

PackageIdentifier: Postman.Postman.Canary
PackageVersion: 9.3.0-canary01
PackageLocale: en-US
Publisher: Postman
PublisherUrl: https://www.postman.com/
PublisherSupportUrl: https://www.postman.com/support
PrivacyUrl: https://www.postman.com/legal/privacy-policy
# Author: 
PackageName: PostmanCanary
PackageUrl: https://www.postman.com/
License: Proprietary
LicenseUrl: https://www.postman.com/legal/terms/
Copyright: Copyright (c) 2021 Postman, Inc. All rights reserved.
# CopyrightUrl: 
ShortDescription: API platform for building and using APIs
Description: Postman is a collaboration platform for API development. Postman's features simplify each step of building an API and streamline collaboration so you can create better APIs — faster.
Moniker: postman-canary
Tags:
- api
- development
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
