# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome.Beta
PackageVersion: 97.0.4692.71
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 66589C8D58AD4E336E5D150C94B9C5AED851F9353449951B216337FCAC7327C4
  ProductCode: '{8DC17595-1637-31C6-8110-7791C9D48316}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: B90AE1FEFA7AC6A49E64A74225AE1EE703245E9AE23DE0CF249A8B217F201AE8
  ProductCode: '{4ECCECFD-3A7D-32DE-8EF4-1FE4D9767279}'
ManifestType: installer
ManifestVersion: 1.1.0
