# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Sandboxie.Plus
PackageVersion: 1.0.6
PackageLocale: en-US
Publisher: http://xanasoft.com/
PublisherUrl: https://xanasoft.com
PublisherSupportUrl: https://github.com/sandboxie-plus/Sandboxie/issues
# PrivacyUrl: 
Author: https://xanasoft.com
PackageName: Sandboxie-Plus
PackageUrl: https://github.com/sandboxie-plus/Sandboxie
License: GNU General Public License v3.0
LicenseUrl: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE
# Copyright: 
CopyrightUrl: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE
ShortDescription: Sandboxie is a sandbox-based isolation software for 32- and 64-bit Windows NT-based operating systems.
Description: |
  Sandboxie is a sandbox-based isolation software for 32- and 64-bit Windows NT-based operating systems.
  It was developed by Sophos (which acquired it from Invincea, which acquired it earlier from the original author Ronen Tzur).
  It creates a sandbox-like isolated operating environment in which applications can be run or installed without permanently modifying the local or mapped drive.
  Such an isolated virtual environment allows controlled testing of untrusted programs and web surfing.
Moniker: sandboxie-plus
Tags:
- sandbox
# Agreements: 
ReleaseNotes: |
  Added
  * replaced "Open with" with a Sandboxie dialog to work on Windows 10 #1138
  * added ability to run Store apps in App Compartment mode (on Windows 11 requires COM to be open)
  * added new debug options "UnstrippedToken=y" and "KeepUserGroup=y"
  * added double click to recover files and folders in recovery window #1466
  * added Ukrainian language on Plus UI (by SuperMaxusa) #1488

  Changed
  * "UseSbieWndStation=y" is now the default behaviour #1442
  * disabled Win32k hooking when HVCI is enabled due to an incompatibility (BSOD) #1483

  Fixed
  * fixed box initialization issue in Privacy mode #1469
  * fixed issue with shortcuts creation introduced in a recent build #1471
  * fixed various issues in Privacy Enhanced boxes and rule specificity
  * fixed issue with SeAccessCheckByType and alike
  * fixed issues with Win32k hooking on 32 bit Windows #1479
  
  Removed
  * removed obsolete SkyNet rootkit detection from 32 bit build
ReleaseNotesUrl: https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.6
ManifestType: defaultLocale
ManifestVersion: 1.1.0
