# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Sandboxie.Plus
PackageVersion: 1.0.6
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2021-12-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.6/Sandboxie-Plus-x64-v1.0.6.exe
  InstallerSha256: 4122AA1076EF4754C73DC2DBD29850C5F658EFCBC9665DA308DA07C3B1A17B11
- Architecture: x86
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.6/Sandboxie-Plus-x86-v1.0.6.exe
  InstallerSha256: 92FF07CD68DD59BA32866750D4B3FACB757A4B3B2815A824A6C6CBAC392F3011
ManifestType: installer
ManifestVersion: 1.1.0
