# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: 360.360zip
PackageVersion: 4.0.0.1380
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- "001"
- "002"
- "003"
- "004"
- "005"
- "006"
- "007"
- "008"
- "009"
- "010"
- "011"
- "012"
- "013"
- "014"
- "015"
- "016"
- "017"
- "018"
- "019"
- "020"
- "021"
- "022"
- "023"
- "024"
- "025"
- "026"
- "027"
- "028"
- "029"
- "030"
- "031"
- "032"
- "033"
- "034"
- "035"
- "036"
- "037"
- "038"
- "039"
- "040"
- "041"
- "042"
- "043"
- "044"
- "045"
- "046"
- "047"
- "048"
- "049"
- "050"
- "051"
- "052"
- "053"
- "054"
- "055"
- "056"
- "057"
- "058"
- "059"
- "060"
- "061"
- "062"
- "063"
- "064"
- "065"
- "066"
- "067"
- "068"
- "069"
- "070"
- "071"
- "072"
- "073"
- "074"
- "075"
- "076"
- "077"
- "078"
- "079"
- "080"
- "081"
- "082"
- "083"
- "084"
- "085"
- "086"
- "087"
- "088"
- "089"
- "090"
- "091"
- "092"
- "093"
- "094"
- "095"
- "096"
- "097"
- "098"
- "099"
- "100"
- 7z
- arj
- bz2
- bzip2
- cab
- cpio
- deb
- dmg
- fat
- gz
- gzip
- hfs
- htfs
- iso
- lha
- lzh
- lzma
- rar
- rpm
- squashfs
- swm
- tar
- taz
- tbz
- tbz2
- tgz
- tpz
- txz
- vhd
- wim
- xar
- xz
- z
- zip
Installers:
- Architecture: x86
  InstallerUrl: https://down.360safe.com/360zip_setup_4.0.0.1380.exe
  InstallerSha256: 6C6359A5805A15C4F7659638AABC154C6C7E98CBF5766CC380E58EF7955FA096
  ProductCode: 360压缩
ManifestType: installer
ManifestVersion: 1.1.0
