# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.1.0.schema.json

PackageIdentifier: 360.360zip
PackageVersion: 4.0.0.1380
PackageLocale: zh-CN
Publisher: 360安全中心
PublisherUrl: https://www.360.cn
PublisherSupportUrl: https://bbs.360.cn/forum.php?mod=forumdisplay&fid=120
PrivacyUrl: http://www.360.cn/privacy/v3/360yasuo.html
Author: 北京奇虎科技有限公司
PackageName: 360压缩
PackageUrl: https://yasuo.360.cn/
License: 免费软件
# LicenseUrl: 
Copyright: (C) 360.cn Inc. All Rights Reserved.
CopyrightUrl: http://www.360.cn/about/banquanshengming.html
ShortDescription: 360 推出的免费解压缩软件
Description: 360 压缩是新一代的压缩软件，永久免费。360 压缩相比传统压缩软件更快更轻巧，支持解压主流的 rar、zip、7z、iso 等多达 42 种压缩文件。360 压缩内置云安全引擎，可以检测木马，更安全。大幅简化了传统软件的繁琐操作，还改进了超过 20 项的使用细节，拥有全新的界面。360 压缩的主要特点是快速轻巧、兼容性好、更安全、更漂亮，而且是永久免费的。
# Moniker: 
Tags:
- "360"
- 7z
- rar
- zip
- 压缩
- 归档
- 解压
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: locale
ManifestVersion: 1.1.0
