# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: 360.360zip
PackageVersion: 4.0.0.1380
PackageLocale: en-US
Publisher: 360安全中心
PublisherUrl: https://www.360.cn
PublisherSupportUrl: https://bbs.360.cn/forum.php?mod=forumdisplay&fid=120
PrivacyUrl: http://www.360.cn/privacy/v3/360yasuo.html
Author: Beijing Qihoo Technology Co., Ltd.
PackageName: 360压缩
PackageUrl: https://yasuo.360.cn/
License: Freeware
# LicenseUrl: 
Copyright: (C) 360.cn Inc. All Rights Reserved.
CopyrightUrl: http://www.360.cn/about/banquanshengming.html
ShortDescription: Free decompression utility by Qihoo 360
Description: 360zip is a new generation of compression utility which is fast, lightweight, compatible, safe, beautiful, and free forever. It is faster and lighter than traditional compression utility and supports decompression of up to 42 mainstream formats of archives such as rar, zip, 7z, and iso. It contains a built-in cloud security engine for detecting Trojan, making your system more secure. It greatly simplifies the complex interactions compared to traditional utilities, improves more than 20 usage details, and provides a brand-new interface.
Moniker: 360zip
Tags:
- "360"
- 7z
- archive
- archiver
- rar
- unachiver
- unzip
- zip
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
