# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 99.0.4800.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: /silent /install
  SilentWithProgress: /silent /install
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/appguid%3D%7B4EA16AC7-FD5A-47C3-875B-DBF4A2008C20%7D%26usagestats%3D1%26ap%3Dx64-canary-statsdef_1/update2/installers/ChromeSetup.exe
  InstallerSha256: E734AF510B7A79D6AA39C99E7C59BB8DF90B5AE3F59969ADC8B20FC1D662D69B
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/appguid%3D%7B4EA16AC7-FD5A-47C3-875B-DBF4A2008C20%7D%26usagestats%3D1%26ap%3D-statsdef_1/update2/installers/ChromeSetup.exe
  InstallerSha256: B0E20FF87348CED21C1D78A9F2ED78C0BECB4C3EE8A4CD5CE55AE9D07D092E7D
ManifestType: installer
ManifestVersion: 1.1.0
