# Automatically updated by the winget bot at 2022/Jan/01
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: RARLab.WinRAR.Beta
PackageVersion: 6.10.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Commands:
- winrar
FileExtensions:
- ‘001’
- 7z
- arj
- bz2
- cab
- gz
- iso
- jar
- lz
- lzh
- rar
- tar
- uue
- xz
- z
- zip
- zipx
Installers:
- Architecture: x64
  InstallerUrl: https://www.rarlab.com/rar/winrar-x64-610b3.exe
  InstallerSha256: 55E966E626F62B22DA7694D8B40BEC5EE674AE4B5ADDDDEF874D57889B2F3085
- Architecture: x86
  InstallerUrl: https://www.rarlab.com/rar/winrar-x32-610b3.exe
  InstallerSha256: 2E580FBB9C3D0E488CB751FA00C518DC1F097E6D3ED091629C8737DE8401FB54
ManifestType: installer
ManifestVersion: 1.1.0
