# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Microsoft.OpenJDK.11
PackageVersion: 11.0.13.8
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/6c20711c-b0c5-4f3c-a334-9d24a6923926/e05ece286a8d30e32b43ca15e84b411a/microsoft-jdk-11.0.13.8.1-windows-x64.msi
  InstallerSha256: A6651E68C945D880D753C08515BE123DA4BBFEC8FE9A684463D2C336268C7FEE
  Scope: machine
  ProductCode: '{3CCA84F4-964E-44E4-B8C1-6AF65AAC80CA}'
  UpgradeBehavior: uninstallPrevious
  InstallerType: msi
  InstallerSwitches:
    Custom: ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome
- Architecture: arm64
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/6c20711c-b0c5-4f3c-a334-9d24a6923926/bf0881765638a300b54c4a8b7e22af14/microsoft-jdk-11.0.13.8.1-windows-aarch64.msi
  InstallerSha256: 67FAECC4AEE9203F767462D1239B1CE2D3E1DCA31ACD0A7A13E9E14E6D7EE62D
  Scope: machine
  ProductCode: '{02511115-0324-450C-A464-9E2E72A7D1A7}'
  UpgradeBehavior: uninstallPrevious
  InstallerType: msi
  InstallerSwitches:
    Custom: ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome
ManifestType: installer
ManifestVersion: 1.0.0
