# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: JetBrains.Space
PackageVersion: 2021.4.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/space/jetbrains-space.exe
  InstallerSha256: 9DAB5365D6C40236782F456C4878F16279D0EEE9AB0E803BBD5C894B15ACEBC6
ManifestType: installer
ManifestVersion: 1.1.0
