# Automatically updated by the winget bot at 2021/Dec/29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: DucFabulous.UltraViewer
PackageVersion: 6.5.4
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://dl2.ultraviewer.net/UltraViewer_setup_6.2_en.exe
  InstallerSha256: 8C54C90B2BFEA894324B6ED8A02B84C9C4AA162AAAAACE66E5E1E03ED3BFB2B0
ManifestType: installer
ManifestVersion: 1.0.0
