# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Nakama.Hamul
PackageVersion: 2.65.0
PackageLocale: en-US
Publisher: Nakama
PackageName: Hamul
License: Copyright © 2021 Nakama
ShortDescription: Make Real Friends, Gaming Together
ManifestType: defaultLocale
ManifestVersion: 1.0.0

