# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.5-1-22000-65
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Wondershare.PDFelement
PackageVersion: 8.3.6
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- pdf
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/pdfelement-pro_full5239.exe
  InstallerSha256: CD884896D3F21077ED732258B6AA398DFDE0D6CE5228DDCE656B325B416B3823
ManifestType: installer
ManifestVersion: 1.1.0
