# Automatically updated by the winget bot at 2021/Dec/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: CyberCat.ADBAppControl
PackageVersion: 1.7.2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
