PackageIdentifier: LutzRoeder.Netron
PackageVersion: 5.4.9
Platform:
- Windows.Desktop
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x86
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.4.9/Netron-Setup-5.4.9.exe
  InstallerSha256: EB961226E844BD075A8057882A7CD2BAB88DB22F64117C1BC921C092F94D41E6
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- Architecture: arm64
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.4.9/Netron-Setup-5.4.9.exe
  InstallerSha256: EB961226E844BD075A8057882A7CD2BAB88DB22F64117C1BC921C092F94D41E6
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
FileExtensions:
- armnn
- caffemodel
- cmf
- dnn
- h5
- hd5
- hdf5
- keras
- lite
- mar
- meta
- mlmodel
- mlpackage
- mnn
- model
- nb
- nn
- om
- onnx
- paddle
- param
- pb
- pbtxt
- pdmodel
- pdparams
- prototxt
- pt
- pth
- ptl
- rknn
- t7
- tfl
- tflite
- tmfile
- uff
- xmodel
ManifestType: installer
ManifestVersion: 1.0.0
